services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./.next:/app/.next
      - ./public:/app/public

volumes:
  next-cache:
